version: '3.7'
services:
  web:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
     - "5000:5000"
    dns: 
     - 8.8.8.8
     - 1.1.1.1
     - 8.8.8.4
    container_name: 'hera_backend_web'
    volumes:
      - .:/app
    depends_on:
     - redis
  redis:
    image: redis